import { Person } from '@/types/types';
import { Rank } from '@/constants/rank';

export const MOCK_PEOPLE: Person[] = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    birth_date: '1990-04-12',
    gender: 'Male',
    phone: '+1 (555) 111-2222',
    parish: 'CCC Parish A',
    email: 'john.doe@example.com',
    rank: Rank.SUPERIOR_EVANGELIST,
    availability: { sundays: true, wednesdays: true },
  },
  {
    id: 2,
    first_name: 'Jane',
    last_name: 'Smith',
    birth_date: '1994-09-03',
    gender: 'Female',
    phone: '+1 (555) 333-4444',
    parish: 'CCC Parish A',
    email: 'jane.smith@example.com',
    rank: Rank.CAPE_ELDER_SISTER,
    availability: { sundays: true, wednesdays: false },
  },
  {
    id: 3,
    first_name: 'Samuel',
    last_name: 'Ade',
    birth_date: '1975-01-20',
    gender: 'Male',
    phone: '+234 700 000 0003',
    parish: 'CCC Parish A',
    email: 'samuel.ade@example.com',
    rank: Rank.SHEPHERD_IN_CHARGE,
    availability: { sundays: true, wednesdays: true, thursdays: true },
  },
  {
    id: 4,
    first_name: 'Peter',
    last_name: 'Okoro',
    birth_date: '1968-07-11',
    gender: 'Male',
    phone: '+234 700 000 0004',
    parish: 'CCC Parish A',
    email: 'peter.okoro@example.com',
    rank: Rank.MOST_VENERABLE_SUPERIOR_EVANGELIST,
    availability: { sundays: true, wednesdays: false },
  },
  {
    id: 5,
    first_name: 'Emmanuel',
    last_name: 'Ayo',
    birth_date: '1980-03-05',
    gender: 'Male',
    phone: '+234 700 000 0005',
    parish: 'CCC Parish A',
    email: 'emmanuel.ayo@example.com',
    rank: Rank.VENERABLE_SUPERIOR_EVANGELIST,
    availability: null,
  },
  {
    id: 6,
    first_name: 'Chinedu',
    last_name: 'Nwosu',
    birth_date: '1985-12-01',
    gender: 'Male',
    phone: '+234 700 000 0006',
    parish: 'CCC Parish A',
    email: 'chinedu.nwosu@example.com',
    rank: Rank.CAPE_ELDER_BROTHER,
    availability: { sundays: true },
  },
  {
    id: 7,
    first_name: 'Olu',
    last_name: 'Bello',
    birth_date: '1992-06-17',
    gender: 'Male',
    phone: '+234 700 000 0007',
    parish: 'CCC Parish A',
    email: 'olu.bello@example.com',
    rank: Rank.BROTHER,
    availability: 'Weekends only',
  },
  {
    id: 8,
    first_name: 'Ada',
    last_name: 'Nne',
    birth_date: '1958-02-14',
    gender: 'Female',
    phone: '+234 700 000 0008',
    parish: 'CCC Parish A',
    email: 'ada.nne@example.com',
    rank: Rank.MOTHER_CELESTIAL,
    availability: { sundays: true, wednesdays: true, fridays: true },
  },
  {
    id: 9,
    first_name: 'Grace',
    last_name: 'Eze',
    birth_date: '1998-11-21',
    gender: 'Female',
    phone: '+234 700 000 0009',
    parish: 'CCC Parish A',
    email: 'grace.eze@example.com',
    rank: Rank.SISTER,
    availability: { sundays: false, wednesdays: true },
  },
  {
    id: 10,
    first_name: 'Blessing',
    last_name: 'Ojo',
    birth_date: '1991-08-30',
    gender: 'Female',
    phone: '+234 700 000 0010',
    parish: 'CCC Parish A',
    email: 'blessing.ojo@example.com',
    rank: Rank.EVANGELIST,
    availability: { sundays: true, thursdays: true },
  },
  // Additional 10 individuals
  {
    id: 11,
    first_name: 'Michael',
    last_name: 'Kalu',
    birth_date: '1982-05-14',
    gender: 'Male',
    phone: '+234 700 000 0011',
    parish: 'CCC Parish B',
    email: 'michael.kalu@example.com',
    rank: Rank.SUPERIOR_EVANGELIST,
    availability: { sundays: false, wednesdays: true },
  },
  {
    id: 12,
    first_name: 'Rebecca',
    last_name: 'Ibe',
    birth_date: '1995-10-02',
    gender: 'Female',
    phone: '+234 700 000 0012',
    parish: 'CCC Parish C',
    email: 'rebecca.ibe@example.com',
    rank: Rank.CAPE_ELDER_SISTER,
    availability: { sundays: true },
  },
  {
    id: 13,
    first_name: 'Daniel',
    last_name: 'Udo',
    birth_date: '1979-09-09',
    gender: 'Male',
    phone: '+234 700 000 0013',
    parish: 'CCC Parish D',
    email: 'daniel.udo@example.com',
    rank: Rank.CAPE_ELDER_BROTHER,
    availability: { sundays: true, thursdays: false },
  },
  {
    id: 14,
    first_name: 'Evelyn',
    last_name: 'Chukwu',
    birth_date: '1988-04-22',
    gender: 'Female',
    phone: '+234 700 000 0014',
    parish: 'CCC Parish E',
    email: 'evelyn.chukwu@example.com',
    rank: Rank.MOTHER_CELESTIAL,
    availability: null,
  },
  {
    id: 15,
    first_name: 'Joshua',
    last_name: 'Ike',
    birth_date: '1993-02-28',
    gender: 'Male',
    phone: '+234 700 000 0015',
    parish: 'CCC Parish F',
    email: 'joshua.ike@example.com',
    rank: Rank.BROTHER,
    availability: { weekends: true },
  },
  {
    id: 16,
    first_name: 'Mercy',
    last_name: 'Ofor',
    birth_date: '1987-12-12',
    gender: 'Female',
    phone: '+234 700 000 0016',
    parish: 'CCC Parish G',
    email: 'mercy.ofor@example.com',
    rank: Rank.SISTER,
    availability: 'Wednesday evenings',
  },
  {
    id: 17,
    first_name: 'Timothy',
    last_name: 'Aden',
    birth_date: '1965-07-07',
    gender: 'Male',
    phone: '+234 700 000 0017',
    parish: 'CCC Parish H',
    email: 'timothy.aden@example.com',
    rank: Rank.VENERABLE_SUPERIOR_EVANGELIST,
    availability: { sundays: true, mondays: true },
  },
  {
    id: 18,
    first_name: 'Rita',
    last_name: 'Anu',
    birth_date: '2000-01-15',
    gender: 'Female',
    phone: '+234 700 000 0018',
    parish: 'CCC Parish I',
    email: 'rita.anu@example.com',
    rank: Rank.CAPE_ELDER_SISTER,
    availability: { sundays: false, fridays: true },
  },
  {
    id: 19,
    first_name: 'Paul',
    last_name: 'Okafor',
    birth_date: '1996-03-03',
    gender: 'Male',
    phone: '+234 700 000 0019',
    parish: 'CCC Parish J',
    email: 'paul.okafor@example.com',
    rank: Rank.EVANGELIST,
    availability: { sundays: true },
  },
  {
    id: 20,
    first_name: 'Naomi',
    last_name: 'Kemi',
    birth_date: '1990-09-09',
    gender: 'Female',
    phone: '+234 700 000 0020',
    parish: 'CCC Parish K',
    email: 'naomi.kemi@example.com',
    rank: Rank.MOTHER_CELESTIAL,
    availability: { weekends: true, wednesdays: false },
  },
];
